name: "sports"
version: "1.0.0"
config-version: 2

profile: "sports"

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
 sports_data:
  staging:
    +materialized: view
    +database: staging

  analytics:
    materialized: table
    database: analytics
