select 
    rosters.team,
    rosters.jerseyNum as jersey_number,
    rosters.pos as position,
    rosters.school,
    rosters.espnName as espn_name,
    rosters.espnID as espn_id,
    rosters.espnLink as espn_link,
    rosters.espnHeadshot as espn_headshot,
    rosters.bDay as birthdate,
    rosters.age,
    rosters.gamesPlayed as games_played,
    rosters."Kicking.fgAttempts" as field_goals_attempted,
    rosters."Kicking.fgMade" as field_goals_made,
    rosters."Kicking.fgYds" as field_goals_yards,
    rosters."fantasyPointsDefault.standard" as standard_fantasy_points,
    rosters."fantasyPointsDefault.PPR" as ppr_fantasy_points,
    rosters."fantasyPointsDefault.halfPPR" as half_ppr_fantasy_points,
    rosters."Defense.totalTackles" as total_tackles,
    rosters."Defense.fumblesLost" as fumbles_lost,
    rosters."Defense.defTD" as defensive_touchdowns,
    rosters."Defense.fumbles",
    rosters."Defense.fumblesRecovered" as defensive_fumbles_recovered,
    rosters."Defense.soloTackles" as solo_tackles,
    rosters."Defense.defensiveInterceptions" as defensive_interceptions,
    rosters."Defense.tfl" as total_fumbles_lost,
    rosters."Defense.sacks" as defensive_sacks,
    rosters."Receiving.receptions" as receptions,
    rosters."Receiving.recTD" as receiving_touchdowns,
    rosters."Receiving.targets" as targets,
    rosters."Receiving.recYds" as receiving_yards,
    rosters."Rushing.rushYds" as rushing_yards,
    rosters."Rushing.carries" as carries,
    rosters."Rushing.rushTD" as rushing_touchdowns,
    rosters."Passing.passAttempts" as passing_attempts,
    rosters."Passing.passTD" as passing_touchdowns,
    rosters."Passing.passYds" as passing_yards,
    rosters."Passing.int" as interceptions,
    rosters."Passing.passCompletions" as completions,
    rosters."Punting.puntYds" as punting_yards,
    rosters."Punting.punts" as punts,
    rosters."Punting.puntsin20" as punts_in_20_yards,
    rosters."Punting.puntTouchBacks" as punt_touchbacks,
    rosters.injDate as injury_date,
    rosters.injReturnDate as injury_return_date,
    rosters.description as injury_description,
    rosters.designation as status
from {{ source('teams', 'rosters') }}
